spring.application.name=inventory-var27

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_var27
spring.datasource.username=laba
spring.datasource.password=laba2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# i18n
spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false

logging.level.ru.lab.inventory=INFO